version: "3"

services:
  axonserver:
    image: axoniq/axonserver:4.5
    ports:
      - "8024:8024"
      - "8124:8124"
    volumes:
      - eventdata:/eventdata
      - data:/data
volumes:
  eventdata:
  data:
